name: CI & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Backend tests ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: backend
        env:
          # 패키지 경로 인식 (pytest에서 app.* 임포트)
          PYTHONPATH: ${{ github.workspace }}/backend
        run: pytest -q

      # ---------- Frontend tests ----------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Deploy Frontend to Vercel ----------
      # 사전에 GitHub 리포지토리 Secrets에 아래 3개 등록:
      # VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
      - name: Deploy Frontend to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel@latest
          cd frontend
          # 환경변수/프로젝트 설정 가져오기
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          # 프로덕션 빌드
          vercel build --prod --token=$VERCEL_TOKEN
          # 사전 빌드 결과 배포
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

      # ---------- Trigger Render Backend Deploy ----------
      # Render Web Service의 Auto-Deploy 기능을 사용하므로, GitHub Actions에서
      # 별도로 배포를 트리거할 필요가 없습니다. GitHub에 푸시하면 Render가
      # 변경 사항을 감지하여 자동으로 배포합니다.
